apiVersion: v1
kind: Service
metadata:
  name: devops-challenge-dotnet-service
spec:
  selector:
    app: devops-challenge-dotnet
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: LoadBalancer
